// Code generated by hertz generator.

package main

import (
	"miniDouyin/biz/dal"
	"miniDouyin/router"
	"miniDouyin/utils"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	dal.Init()

	h := server.Default(
		server.WithHostPorts(string("0.0.0.0:")+utils.PORT),
		server.WithMaxRequestBodySize(utils.MaxBody),
	)

	router.Register(h)

	h.Spin()
}
