// Code generated by hertz generator.

package main

import (
	"miniDouyin/biz/dal"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	dal.Init()

	h := server.Default(server.WithHostPorts("0.0.0.0:8889"))

	register(h)
	h.Spin()
}
